const dataStructures = ["data-structure/data-unit"];

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // autogeneratedSidebar: [{ type: "autogenerated", dirName: "." }],
  docs: [
    "intro",
    {
      type: "category",
      label: "자료구조",
      items: dataStructures,
    },
  ],
};

module.exports = sidebars;
